# Generated by Django 4.2.1 on 2023-05-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_id",
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
