# Generated by Django 4.2.1 on 2023-05-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_remove_wiki_title_id_wiki_wiki_detail"),
        ("wiki", "0004_wiki_user_id_alter_wiki_title_id"),
    ]

    operations = []
