# Generated by Django 4.2.1 on 2023-05-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki_detail", "0002_rename_name_wiki_detail_title"),
        ("wiki", "0005_merge_20230522_1614"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wiki",
            name="wiki_detail",
            field=models.ManyToManyField(
                blank=True, related_name="wiki", to="wiki_detail.wiki_detail"
            ),
        ),
    ]
