databases:
  - name: ajou-wiki
    databaseName: ajou-wiki
    user: ajou-wiki
    region: singapore

services:
  - type: web
    name: ajou-wiki
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ajou-wiki
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4  