# Generated by Django 4.2.1 on 2023-05-22 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0005_merge_20230522_1614"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="wiki_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag",
                to="wiki.wiki",
            ),
        ),
    ]
