# Generated by Django 4.2.1 on 2023-05-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_tag_wiki_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
