# Generated by Django 4.2.1 on 2023-05-31 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wikis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wiki_Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="", max_length=30)),
                ("order", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wiki_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wiki_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_details",
                        to="wikis.wiki",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
