# Generated by Django 4.2.1 on 2023-05-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wikis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wiki",
            name="detail_id",
        ),
    ]
